from libghdl import libghdl

Replace_Text = libghdl.files_map__editor__replace_text_ptr
Fill_Text = libghdl.files_map__editor__fill_text_ptr

Check_Buffer_Content = libghdl.files_map__editor__check_buffer_content
