#!/bin/sh

{
echo "/* This file is automatically generated by build_header.sh - DO NOT MODIFY */"
echo "enum Module_Id {"
grep -h "constant Module_Id :=" netlists.ads netlists-gates.ads | sed -e '/constant Module_Id :=/s/:.*://' -e 's/;/,/' -e 's/ *--.*$//'
echo "};"
} > ghdlsynth_gates.h
