.. |SHIELD:travis-ci| image:: https://img.shields.io/travis/ghdl/ghdl/master.svg?longCache=true&style=flat-square&logo=travis
   :target: https://travis-ci.org/ghdl/ghdl
   :alt: Build status by Travis-CI

.. |SHIELD:appveyor| image:: https://img.shields.io/appveyor/ci/tgingold/ghdl-psgys/master.svg?longCache=true&style=flat-square&logo=appveyor&logoColor=aab2ab
   :target: https://ci.appveyor.com/project/tgingold/ghdl-psgys/branch/master
   :alt: Build status by AppVeyor

.. |SHIELD:release| image:: https://img.shields.io/github/release/ghdl/ghdl.svg?longCache=true&style=flat-square&label=latest%20release
   :target: https://github.com/ghdl/ghdl/releases
   :alt: Latest release

.. |SHIELD:code-lic| image:: https://img.shields.io/badge/code%20license-GPLv2-bd0000.svg?longCache=true&style=flat-square&label=license&logo=gnu
   :target: Licenses.html
   :alt: GNU General Public License 2

.. |SHIELD:doc-lic| image:: https://img.shields.io/badge/doc%20license-CC--BY--SA--4.0-aab2ab.svg?longCache=true&style=flat-square
   :target: Licenses.html
   :alt: Creative Commons Attribution-ShareAlike 4.0

.. |SHIELD:gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=4db797
   :target: https://gitter.im/ghdl1/Lobby
   :alt: Talk to us on Gitter

.. |SHIELD:issues-new| image:: https://img.shields.io/badge/new-issue-yellowgreen.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/issues/new
   :alt: Open new issue at GitHub

.. |SHIELD:new-pr| image:: https://img.shields.io/badge/new-pull--request-yellowgreen.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/compare/
   :alt: Open new Pull Request (PR) at GitHub

.. |SHIELD:bug-report| image:: https://img.shields.io/badge/new-bug--report-yellowgreen.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/issues/new?template=bug_report.md
   :alt: Open new bug report at GitHub

.. |SHIELD:feature-request| image:: https://img.shields.io/badge/new-feature--request-yellowgreen.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/issues/new?template=feature_request.md
   :alt: Open new feature request at GitHub

.. |SHIELD:issues-open| image:: https://img.shields.io/github/issues/ghdl/ghdl.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/issues
   :alt: Open issues

.. |SHIELD:issues-closed| image:: https://img.shields.io/github/issues-closed-raw/ghdl/ghdl.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/issues?q=is%3Aissue+is%3Aclosed
   :alt: Closed issues

.. |SHIELD:issues-pr| image:: https://img.shields.io/github/issues-pr/ghdl/ghdl.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/pulls
   :alt: Open pull requests

.. |SHIELD:issues-pr-closed| image:: https://img.shields.io/github/issues-pr-closed-raw/ghdl/ghdl.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/pulls
   :alt: Closed pull requests

.. |SHIELD:contributors| image:: https://img.shields.io/github/contributors/ghdl/ghdl.svg?longCache=true&style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl/graphs/contributors
   :alt: Contributors

.. |SHIELD:gh-logo| image:: https://img.shields.io/badge/-ghdl/ghdl-323131.svg?style=flat-square&logo=github
   :target: https://github.com/ghdl/ghdl
   :alt: Source Code on GitHub
